import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import RailroadMap from "../components/RailRoadMap"
import { useEffect, useState } from "react"
import {
  bunkiRailId,
  BunkiRailId,
  Message,
  stopRailId,
  StopRailId,
} from "../types/websocket-messages"
import SpeedMeter from "../components/svgParts/SpeedMeter"

// OFF: false, ON: trueと対応
type StopPointState = Record<StopRailId, boolean>
const INITIAL_STOP_POINT_STATE: StopPointState = {
  motoyawata_s1: false,
  motoyawata_s2: false,
  motoyawata_s3: false,
  motoyawata_s4: false,
  motoyawata_s5: false,
  motoyawata_s6: false,
  iwamotocho_s1: false,
  iwamotocho_s2: false,
  iwamotocho_s4: false,
  kudanshita_s5: false,
  kudanshita_s6: false,
  sasazuka_s1: false,
  sasazuka_s2: false,
  sasazuka_s3: false,
  sasazuka_s4: false,
  sasazuka_s5: false,
  meidaimae_s1: false,
  meidaimae_s2: false,
  chofu_s1: false,
  chofu_s2: false,
  chofu_s3: false,
  chofu_s4: false,
  chofu_s5: false,
  chofu_s6: false,
  kitano_s1: false,
  kitano_s2: false,
  kitano_s3: false,
  kitano_s4: false,
  kitano_s5: false,
  kitano_s6: false,
  takao_s1: false,
  takao_s2: false,
}

type SwitchPointState = Record<BunkiRailId, boolean>
const INITIAL_SWITCH_POINT_STATE: SwitchPointState = {
  iwamotocho_b1: false,
  iwamotocho_b2: false,
  iwamotocho_b3: false,
  iwamotocho_b4: false,
  sasazuka_b1: false,
  sasazuka_b2: false,
  chofu_b1: false,
  chofu_b2: false,
  chofu_b3: false,
  chofu_b4: false,
  chofu_b5: false,
  kitano_b1: false,
  kitano_b2: false,
  kitano_b3: false,
  kitano_b4: false,
}

const Home: NextPage = () => {
  const [stopPointState, setStopPointState] = useState<StopPointState>(
    INITIAL_STOP_POINT_STATE
  )
  const [isStopPoint1, setIsStopPoint1] = useState<boolean>(true)
  const [isStopPoint2, setIsStopPoint2] = useState<boolean>(true)
  const [isStopPoint3, setIsStopPoint3] = useState<boolean>(true)
  const [isStopPoint4, setIsStopPoint4] = useState<boolean>(true)
  const [switchPointState, setSwitchPointState] = useState<SwitchPointState>(
    INITIAL_SWITCH_POINT_STATE
  )
  const [isLeftSwichPoint1, setIsLeftSwitchPoint1] = useState<boolean>(true)
  const [isLeftSwichPoint2, setIsLeftSwitchPoint2] = useState<boolean>(true)
  const [trainPosition1, setTrainPosition1] = useState<number>(0.4)

  useEffect(() => {
    const ws = new WebSocket("wss://control.chofufes2021.gotti.dev/ws")
    ws.addEventListener("open", (e) => {
      console.log("opened")
      console.log(e)
    })
    ws.addEventListener("message", (e) => {
      console.log("recieved message")
      console.log(e)
      const message: Message = JSON.parse(e.data)
      console.log(message)
      if (message.station_name === "unknown" || message.state === "UNKNOWN") {
        return
      }
      if (stopRailId.is(message.station_name)) {
        setStopPointState((previousStopPointState) => ({
          ...previousStopPointState,
          [message.station_name]: message.state === "ON",
        }))
        return
      }
      if (bunkiRailId.is(message.station_name)) {
        setSwitchPointState((previousSwitchPointState) => ({
          ...previousSwitchPointState,
          [message.station_name]: message.state === "ON",
        }))
      }
    })
    ws.addEventListener("error", (e) => {
      console.log("error occured")
      console.log(e)
    })
    ws.addEventListener("close", (e) => {
      console.log("closed")
      console.log(e)
    })
    return () => {
      ws.close()
    }
  }, [])

  useEffect(() => {
    const intervalId = setInterval(() => {
      const tmpTrainPosition1 = trainPosition1 + 0.01
      setTrainPosition1(tmpTrainPosition1 <= 1 ? tmpTrainPosition1 : 0)
    }, 20)
    return () => clearInterval(intervalId)
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>工研&times;鉄研プラレール展示 操作ページ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kokenLogo.ico" />
      </Head>

      <header>
        <h1 className={styles.title}>
          工研&times;鉄研プラレール展示 操作ページ
        </h1>
      </header>

      <main className={styles.main}>
        <section>
          <h2>映像部分</h2>
          <div>(video予定地)</div>
        </section>

        <section>
          <h2>地図部分</h2>
          <RailroadMap
            datas={{
              stop: stopPointState,
              stop1: isStopPoint1,
              stop2: isStopPoint2,
              stop3: isStopPoint3,
              stop4: isStopPoint4,
              switchState: switchPointState,
              switch1: isLeftSwichPoint1,
              switch2: isLeftSwichPoint2,
              train1: {
                positionScale: trainPosition1,
                id: "koken",
              },
            }}
          />
        </section>

        <section>
          <h2>操作部分</h2>
          <svg viewBox="0 0 100 100">
            <SpeedMeter cx={50} cy={50} r={40} max={100} value={30} />
          </svg>
          <button onClick={() => setIsLeftSwitchPoint1(!isLeftSwichPoint1)}>
            分岐点1切り替え
          </button>
          <button onClick={() => setIsLeftSwitchPoint2(!isLeftSwichPoint2)}>
            分岐点2切り替え
          </button>
          <button onClick={() => setIsStopPoint1(!isStopPoint1)}>
            ストップレール1切り替え
          </button>
          <button onClick={() => setIsStopPoint2(!isStopPoint2)}>
            ストップレール2切り替え
          </button>
          <button onClick={() => setIsStopPoint3(!isStopPoint3)}>
            ストップレール3切り替え
          </button>
          <button onClick={() => setIsStopPoint4(!isStopPoint4)}>
            ストップレール4切り替え
          </button>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.koken.club.uec.ac.jp/"
          target="_blank"
          rel="noopener noreferrer"
        >
          &copy;2021 電気通信大学工学研究部
        </a>
      </footer>
    </div>
  )
}

export default Home
