import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import RailroadMap from "../components/RailRoadMap"
import { useEffect, useState } from "react"

const Home: NextPage = () => {
  const [isStopPoint1, setIsStopPoint1] = useState<boolean>(true)
  const [isStopPoint2, setIsStopPoint2] = useState<boolean>(true)
  const [isLeftSwichPoint1, setIsLeftSwitchPoint1] = useState<boolean>(true)
  const [isLeftSwichPoint2, setIsLeftSwitchPoint2] = useState<boolean>(true)
  const [trainPosition1, setTrainPosition1] = useState<number>(0.4)
  const [isStopStation1, setIsStopStation1] = useState<boolean>(true)
  const [isStopStation2, setIsStopStation2] = useState<boolean>(true)
  const [isStopStation3, setIsStopStation3] = useState<boolean>(true)

  useEffect(() => {
    const intervalId = setInterval(
      () => {
        const tmpTrainPosition1 = trainPosition1 + 0.01;
        setTrainPosition1(tmpTrainPosition1 <= 1 ? tmpTrainPosition1 : 0);
      },
      20
    )
    return () => clearInterval(intervalId)
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>工研&times;鉄研プラレール展示 操作ページ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/kokenLogo.ico" />
      </Head>

      <header>
        <h1 className={styles.title}>
          工研&times;鉄研プラレール展示 操作ページ
        </h1>
      </header>

      <main className={styles.main}>
        <section>
          <h2>映像部分</h2>
          <div>(video予定地)</div>
        </section>

        <section>
          <h2>地図部分</h2>
          <RailroadMap
            datas={{
              stop1: isStopPoint1,
              stop2: isStopPoint2,
              switch1: isLeftSwichPoint1,
              switch2: isLeftSwichPoint2,
              train1: {
                positionScale: trainPosition1,
                id: "koken",
              },
              station1: isStopStation1,
              station2: isStopStation2,
              station3: isStopStation3,
            }}
          />
        </section>

        <section>
          <h2>操作部分</h2>
          <button onClick={() => setIsLeftSwitchPoint1(!isLeftSwichPoint1)}>
            分岐点1切り替え
          </button>
          <button onClick={() => setIsLeftSwitchPoint2(!isLeftSwichPoint2)}>
            分岐点2切り替え
          </button>
          <button onClick={() => setIsStopPoint1(!isStopPoint1)}>
            ストップレール1切り替え
          </button>
          <button onClick={() => setIsStopPoint2(!isStopPoint2)}>
            ストップレール2切り替え
          </button>
          <button onClick={() => setIsStopStation1(!isStopStation1)}>
            東京駅切り替え
          </button>
          <button onClick={() => setIsStopStation2(!isStopStation2)}>
            札幌駅切り替え
          </button>
          <button onClick={() => setIsStopStation3(!isStopStation3)}>
            那覇駅切り替え
          </button>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.koken.club.uec.ac.jp/"
          target="_blank"
          rel="noopener noreferrer"
        >
          &copy;2021 電気通信大学工学研究部
        </a>
      </footer>
    </div>
  )
}

export default Home
