import type { NextPage } from "next"
import Head from "next/head"
import styles from "../styles/Home.module.css"
import RailroadMap from "../components/RailRoadMap"
import { useEffect, useState } from "react"

const Home: NextPage = () => {
  const [isStopPoint, setIsStopPoint] = useState<boolean>(true)
  const [isLeftSwichPoint, setIsLeftSwitchPoint] = useState<boolean>(true)
  const [trainPosition1, setTrainPosition1] = useState<number>(0.4)
  const [isStopStation1, setIsStopStation1] = useState<boolean>(true)
  const [isStopStation2, setIsStopStation2] = useState<boolean>(true)
  const [isStopStation3, setIsStopStation3] = useState<boolean>(true)

  useEffect(() => {
    const intervalId = setInterval(
      () => setTrainPosition1((trainPosition1 + 0.01) % 1),
      20
    )
    return () => clearInterval(intervalId)
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <RailroadMap
          datas={{
            stop1: isStopPoint,
            switch1: isLeftSwichPoint,
            train1: {
              positionScale: trainPosition1,
              id: "koken",
            },
            station1: isStopStation1,
            station2: isStopStation2,
            station3: isStopStation3,
          }}
        />
        <button onClick={() => setIsLeftSwitchPoint(!isLeftSwichPoint)}>
          分岐点切り替え
        </button>
        <button onClick={() => setIsStopPoint(!isStopPoint)}>
          ストップレール切り替え
        </button>
        <button onClick={() => setIsStopStation1(!isStopStation1)}>
          東京駅切り替え
        </button>
        <button onClick={() => setIsStopStation2(!isStopStation2)}>
          札幌駅切り替え
        </button>
        <button onClick={() => setIsStopStation3(!isStopStation3)}>
          那覇駅切り替え
        </button>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
