FROM golang:1.19.1-bullseye AS builder

ENV CGO_ENABLED=0
WORKDIR /speed
COPY ./go.mod ./go.sum /speed/
RUN go mod download
COPY . /speed
RUN go build -o /speed/app ./cmd/main.go

FROM gcr.io/distroless/static-debian11:nonroot AS runner
COPY --from=builder --chown=nonroot:nonroot /speed/app /speed
ENTRYPOINT [ "/speed" ]
