FROM nginx
RUN apt-get update && apt-get -y install nodejs npm
COPY ./ /usr/share/nginx/html/
COPY ./skyway_receiver.html /usr/share/nginx/html/index.html

CMD ["bash", "/usr/share/nginx/html/receiver.sh"]
